# This workflow
# - installs Python dependencies,
# - sorts imports,
# - lints code,
# - formats code,
# - runs tests,
# - checks Python type hints, and
# - verifies the build.
#
# These steps are run for each supported Python version, plus the latest version.

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.x']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Sort imports
      run: poetry run sort
    - name: Lint Code
      run: poetry run lint
    - name: Format Code
      run: poetry run format
    - name: Run Tests
      run: poetry run test
    - name: Type Check
      run: poetry run type
    - name: Verify
      run: poetry run checkall
